name:                 Practica03
version:              0.1.0.0
visibility:           public
id:                   Practica03-0.1.0.0-inplace
key:                  Practica03-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           eduardovar1090@ciencias.unam.mx
author:               EduardoVrP
abi:                  inplace
exposed:              True
exposed-modules:      Practica03
import-dirs:
    /home/tania/Escritorio/Logica/LC2026-2-Practica03/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica03-0.1.0.0/build

library-dirs:
    /home/tania/Escritorio/Logica/LC2026-2-Practica03/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica03-0.1.0.0/build

library-dirs-static:
    /home/tania/Escritorio/Logica/LC2026-2-Practica03/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica03-0.1.0.0/build

dynamic-library-dirs:
    /home/tania/Escritorio/Logica/LC2026-2-Practica03/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica03-0.1.0.0/build

data-dir:             /home/tania/Escritorio/Logica/LC2026-2-Practica03/.
hs-libraries:         HSPractica03-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /home/tania/Escritorio/Logica/LC2026-2-Practica03/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica03-0.1.0.0/doc/html/Practica03/Practica03.haddock

haddock-html:
    /home/tania/Escritorio/Logica/LC2026-2-Practica03/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica03-0.1.0.0/doc/html/Practica03
